import React, { useMemo, useRef, useState } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter, type Href } from 'expo-router';
import { ScrollView } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Input, Text, XStack, YStack, useTheme } from 'tamagui';

import { glass } from '../../brand/tokens';
import { AppBackground, GlassCard, GlassDivider } from '../../src/components/Glass';
import { ProfileAvatar } from '../../src/components/ProfileAvatar';
import { TAB_BAR_CLEARANCE, TabBar } from '../../src/components/TabBar';
import {
  DEMOS,
  GROUP_LABELS,
  GROUP_ORDER,
  SEGMENTS,
  type Demo,
  type DemoGroup,
  type DemoRoute,
} from '../../src/demos/catalog';

type Segment = (typeof SEGMENTS)[number]['key'];

const READY_COUNT = DEMOS.filter((demo) => demo.ready).length;

function SectionLabel({ children }: { children: string }) {
  return (
    <Text ml="$4" color="$text2" fontSize={13} lineHeight={18}>
      {children}
    </Text>
  );
}

function DemoRow({ demo, onOpen }: { demo: Demo; onOpen: (route: DemoRoute) => void }) {
  const theme = useTheme();

  // An upcoming capability is inert on purpose: no press handler, no chevron,
  // muted palette. A row that navigated to a page faking the capability would
  // be worse than no row at all in a demonstrator.
  if (!demo.ready) {
    return (
      <XStack
        items="center"
        gap="$3"
        px="$4"
        py="$3"
        minH={56}
        aria-label={`${demo.title} — ${demo.subtitle} — bientôt disponible`}
        aria-disabled
      >
        <YStack
          width={30}
          height={30}
          rounded="$4"
          items="center"
          justify="center"
          bg={glass.muted.iconFill}
        >
          <Ionicons name={demo.icon} size={18} color={glass.muted.iconGlyph} />
        </YStack>
        <YStack flex={1} gap="$0.5">
          <Text color={glass.muted.title} fontSize={17} lineHeight={22} fontWeight="600">
            {demo.title}
          </Text>
          <Text color={glass.muted.subtitle} fontSize={15} lineHeight={20}>
            {demo.subtitle}
          </Text>
        </YStack>
        <YStack px="$2.5" py="$1" rounded={9999} bg={glass.muted.badgeFill}>
          <Text color={glass.muted.badgeText} fontSize={11} lineHeight={15} fontWeight="600">
            Bientôt
          </Text>
        </YStack>
      </XStack>
    );
  }

  return (
    <XStack
      items="center"
      gap="$3"
      px="$4"
      py="$3"
      minH={56}
      pressStyle={{ bg: 'rgba(120,120,128,0.08)' }}
      onPress={() => onOpen(demo.route)}
      role="button"
      aria-label={`${demo.title} — ${demo.subtitle}`}
    >
      <YStack width={30} height={30} rounded="$4" items="center" justify="center" bg="$accentSoft">
        <Ionicons name={demo.icon} size={18} color={theme.accentBase.val} />
      </YStack>
      <YStack flex={1} gap="$0.5">
        <Text color="$text0" fontSize={17} lineHeight={22} fontWeight="600">
          {demo.title}
        </Text>
        <Text color="$text2" fontSize={15} lineHeight={20}>
          {demo.subtitle}
        </Text>
      </YStack>
      <Ionicons name="chevron-forward" size={16} color={theme.text3.val} />
    </XStack>
  );
}

export default function HomeScreen() {
  const router = useRouter();
  const theme = useTheme();
  const [query, setQuery] = useState('');
  const [segment, setSegment] = useState<Segment>('all');

  // One-shot navigation lock: a double tap on a row must not push the same
  // route twice. Released when the list regains focus.
  const navLockRef = useRef(false);

  useFocusEffect(
    React.useCallback(() => {
      navLockRef.current = false;
    }, []),
  );

  const openDemo = React.useCallback(
    (route: DemoRoute) => {
      if (navLockRef.current) return;
      navLockRef.current = true;
      // Cast: .expo/types/router.d.ts is regenerated by Metro, so the routes
      // added in this change are not in the typed-route union until the next
      // `npm run dev`. The values themselves are checked by DemoRoute.
      router.push(route as Href);
    },
    [router],
  );

  const grouped = useMemo(() => {
    const needle = query.trim().toLowerCase();
    const matches = (demo: Demo) =>
      (segment === 'all' || segment === demo.group) &&
      (!needle || `${demo.title} ${demo.subtitle}`.toLowerCase().includes(needle));

    return GROUP_ORDER.map((group) => ({
      group,
      demos: DEMOS.filter((demo) => demo.group === group && matches(demo)),
    })).filter((section) => section.demos.length > 0);
  }, [query, segment]);

  const isEmpty = grouped.length === 0;

  return (
    <AppBackground>
      <SafeAreaView edges={['top']} style={{ flex: 1 }}>
        <YStack flex={1}>
          <YStack px="$4" pt="$2" gap="$1">
            <XStack items="flex-end" justify="space-between" gap="$3">
              <Text flex={1} color="$text0" fontSize={34} lineHeight={41} fontWeight="700">
                Démos
              </Text>
              <ProfileAvatar />
            </XStack>
            <Text color="$text2" fontSize={15} lineHeight={20}>
              {READY_COUNT} capacités natives disponibles, {DEMOS.length - READY_COUNT} à venir
            </Text>

            <GlassCard mt="$3" height={44} rounded="$5">
              <XStack flex={1} items="center" gap="$2" px="$3">
                <Ionicons name="search" size={18} color={theme.text3.val} />
                <Input
                  unstyled
                  flex={1}
                  height={44}
                  borderWidth={0}
                  bg="transparent"
                  color="$text0"
                  placeholder="Rechercher une démo"
                  placeholderTextColor="$text2"
                  value={query}
                  onChangeText={setQuery}
                  fontSize={17}
                  lineHeight={22}
                  aria-label="Rechercher une démo"
                />
              </XStack>
            </GlassCard>

            <GlassCard
              mt="$2.5"
              height={32}
              rounded="$4"
              p="$0.5"
              bg={glass.segment.track}
              borderColor={glass.segment.trackBorder}
              highlight={false}
            >
              <XStack flex={1} gap="$0.5">
                {SEGMENTS.map((item) => {
                  const active = segment === item.key;
                  return (
                    <YStack
                      key={item.key}
                      flex={1}
                      rounded="$3"
                      items="center"
                      justify="center"
                      bg={active ? glass.segment.thumb : 'transparent'}
                      boxShadow={active ? glass.segment.thumbShadow : undefined}
                      onPress={() => setSegment(item.key)}
                      role="button"
                      aria-label={`Filtrer : ${item.label}`}
                    >
                      <Text color="$text0" fontSize={14} fontWeight={active ? '600' : '400'}>
                        {item.label}
                      </Text>
                    </YStack>
                  );
                })}
              </XStack>
            </GlassCard>
          </YStack>

          <ScrollView
            contentContainerStyle={{
              padding: 16,
              paddingTop: 20,
              paddingBottom: TAB_BAR_CLEARANCE,
            }}
          >
            <YStack gap="$5">
              {grouped.map((section) => (
                <YStack key={section.group} gap="$1.5">
                  <SectionLabel>{GROUP_LABELS[section.group as DemoGroup]}</SectionLabel>
                  <GlassCard rounded="$6">
                    {section.demos.map((demo, index) => (
                      <YStack key={demo.id}>
                        {index > 0 && <GlassDivider inset={58} />}
                        <DemoRow demo={demo} onOpen={openDemo} />
                      </YStack>
                    ))}
                  </GlassCard>
                </YStack>
              ))}

              {isEmpty && (
                <YStack py="$9" px="$5" items="center" gap="$1">
                  <Text color="$text0" fontSize={17} lineHeight={22} fontWeight="600">
                    Aucune démo
                  </Text>
                  <Text color="$text2" fontSize={15} lineHeight={20} text="center">
                    {query.trim()
                      ? 'Essayez un autre mot-clé.'
                      : 'Aucune démo dans cette catégorie pour le moment.'}
                  </Text>
                </YStack>
              )}
            </YStack>
          </ScrollView>
        </YStack>
      </SafeAreaView>
      <TabBar />
    </AppBackground>
  );
}
