// Auto-generated by /design-system — do not hand-edit without running drift check
// Direction: iOS-native démonstrateur | Generated: 2026-09-22
// Source: Claude Design canvas "Power Apps Mobile — démonstrateur"
// https://claude.ai/artifact/WSP9Pq7yjg4RrQqP86cgJw

export const tokens = {
  color: {
    bg: '#f2f2f7',
    surface: '#ffffff',
    primary: '#742774',
    accent: '#742774',
    text: '#000000',
    textMuted: '#6c6c70',
    border: '#c6c6c8',
    statusSuccess: '#1d7a35',
    statusWarning: '#9a5000',
    statusDanger: '#c9252d',
    statusInfo: '#0f6cbd',
  },
  space: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    '2xl': 32,
    '3xl': 48,
    '4xl': 64,
  },
  size: {
    buttonHeight: 50,
    inputHeight: 44,
    listRowHeight: 56,
    iconSize: 24,
    avatarSm: 32,
    avatarMd: 40,
    avatarLg: 56,
  },
  radius: {
    sm: 8,
    md: 10,
    lg: 14,
    full: 9999,
  },
  typography: {
    display: { family: 'System', size: 34, weight: '700', lineHeight: 1.21, tracking: 0.37 },
    heading: { family: 'System', size: 22, weight: '700', lineHeight: 1.27, tracking: 0.35 },
    title: { family: 'System', size: 17, weight: '600', lineHeight: 1.29, tracking: -0.41 },
    body: { family: 'System', size: 17, weight: '400', lineHeight: 1.29, tracking: -0.41 },
    bodySm: { family: 'System', size: 15, weight: '400', lineHeight: 1.33, tracking: -0.24 },
    caption: { family: 'System', size: 13, weight: '400', lineHeight: 1.38, tracking: -0.08 },
    mono: { family: 'Menlo', size: 14, weight: '400', lineHeight: 1.4, tracking: 0 },
  },
} as const;

export type BrandTokens = typeof tokens;

/**
 * Glassmorphism layer — transcribed from the Claude Design prototype
 * "Power Apps Mobile.dc.html" (2026-09-22 update).
 *
 * These live outside `tokens` on purpose: `tamagui.config.ts` feeds `tokens`
 * into `createPowerAppsTamaguiConfig`, which only understands space/size/radius
 * /color scales. The glass recipe is a *composition* (fill + hairline border +
 * inset highlight + drop shadow), not a single colour, so it is consumed by the
 * `Glass*` components in `src/components/Glass.tsx` rather than by a theme key.
 *
 * NOTE ON BLUR: the prototype uses `backdrop-filter: blur(26px) saturate(185%)`.
 * React Native has no equivalent, and `expo-blur` is NOT in the template —
 * adding it would cross the native-module boundary (hard rule 2). The look is
 * therefore reproduced with translucent fills + an inset highlight + soft
 * shadows, and the background orbs are faked with stacked concentric circles
 * instead of a real Gaussian blur. Do not "fix" this by installing expo-blur.
 */
export const glass = {
  /** Full-screen canvas gradient — 165° in CSS, top-left → bottom-right here. */
  canvas: ['#f7f2f9', '#eef0f9', '#fbf1ec'] as const,
  canvasStops: [0, 0.46, 1] as const,

  /** The soft colour washes floating over the canvas. */
  orbs: {
    violet: { color: '#a86bb0', opacity: 0.34 },
    blue: { color: '#6b8fd6', opacity: 0.26 },
    amber: { color: '#e0a06a', opacity: 0.26 },
  },

  /** The repeated card surface. */
  surface: {
    fill: 'rgba(255,255,255,0.63)', // #ffffffa1
    border: 'rgba(255,255,255,0.72)', // #ffffffb8
    highlight: 'rgba(255,255,255,0.80)', // #ffffffcc, 1px inset top
    shadow: '0px 6px 20px rgba(26,18,48,0.07)',
  },

  /** Floating tab bar — thinner fill, stronger highlight. */
  bar: {
    fill: 'rgba(255,255,255,0.54)', // #ffffff8a
    border: 'rgba(255,255,255,0.72)',
    highlight: 'rgba(255,255,255,0.85)',
    shadow: '0px 10px 28px rgba(26,18,48,0.12)',
    /** Unselected tab label — 8.1:1 on the pill fill, comfortably AA. */
    inactiveLabel: '#4a4952',
  },

  /** Menus, contextual cards and bottom sheets sit above everything. */
  overlay: {
    fill: 'rgba(255,255,255,0.75)', // #ffffffbf
    border: 'rgba(255,255,255,0.80)',
    scrim: 'rgba(0,0,0,0.35)',
  },

  /** Segmented control: recessed track, raised selected thumb. */
  segment: {
    track: 'rgba(255,255,255,0.44)', // #ffffff70
    trackBorder: 'rgba(255,255,255,0.65)', // #ffffffa6
    thumb: 'rgba(255,255,255,0.88)', // #ffffffe0
    thumbShadow: '0px 1px 3px rgba(26,18,48,0.14)',
  },

  /** Dark media panel behind every demo hero. */
  media: {
    fill: 'rgba(28,28,30,0.82)', // #1c1c1ed1
    border: 'rgba(255,255,255,0.18)', // #ffffff2e
    stripe: 'rgba(255,255,255,0.03)',
  },

  /** Near-black tile a monochrome brand mark sits on (GitHub). */
  brandTile: {
    fill: '#1c1c1e',
    glyph: '#ffffff',
  },

  /** "Bientôt" rows — a capability the template does not ship yet. */
  muted: {
    title: '#8e8e93',
    subtitle: '#aeaeb2',
    iconFill: 'rgba(120,120,128,0.12)',
    iconGlyph: '#aeaeb2',
    badgeFill: 'rgba(120,120,128,0.14)',
    badgeText: '#6c6c70',
  },
} as const;

export type GlassTokens = typeof glass;
